# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '18 18 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache hexo db
      uses: actions/cache@v3
      env:
        cache-name: cache-hexo-db
      with:
        path: ./db.json
        key: ${{ runner.os }}-hexodb-${{ hashFiles('db.json', 'package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-hexodb-

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build --if-present

    - name: deploy to server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        FOLDER: "./public/"
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USERNAME: ${{ secrets.USERNAME }}
        SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}

    - name: notify
      uses: appleboy/telegram-action@0.0.7
      with:
        to: ${{ secrets.TELEGRAM_TO  }}
        token: ${{ secrets.TELEGRAM_TOKEN  }}
        message: Blog deployed.
